# Generated by Django 4.2.7 on 2023-11-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="user-profile-images/"
            ),
        ),
    ]
