# Generated by Django 4.2.7 on 2023-11-22 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=200)),
                ("bank_name", models.CharField(max_length=200)),
                ("bank_code", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Info",
                "verbose_name_plural": "Bank Info",
            },
        ),
    ]
