# Generated by Django 4.2.7 on 2023-11-23 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_client_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contact",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
