# Generated by Django 4.2.7 on 2023-11-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_client_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact",
            field=models.CharField(max_length=50),
        ),
    ]
