# Generated by Django 4.2.7 on 2023-11-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_alter_client_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(default="hi@gmail.com", max_length=254),
        ),
    ]
