# Generated by Django 4.2.7 on 2023-11-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_client_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
