# Generated by Django 4.2.7 on 2023-11-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_alter_client_contact"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="country",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="state",
        ),
        migrations.AddField(
            model_name="payment",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
