# Generated by Django 4.2.7 on 2023-11-23 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_client_contact"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-issue_date",)},
        ),
        migrations.RemoveField(
            model_name="order",
            name="created",
        ),
        migrations.RemoveField(
            model_name="order",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated",
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.client",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="issue_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
