# Generated by Django 4.2.7 on 2023-11-23 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_client_contact"),
        ("order", "0002_alter_order_options_remove_order_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(default="hi"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("SERVICES", "SERVICES"), ("SALES", "SALES")],
                default="SERVICES",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="client.client"
            ),
        ),
    ]
