# Generated by Django 4.2.7 on 2023-11-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_description_order_order_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("SERVICES", "SERVICES"), ("SALES", "SALES")], max_length=10
            ),
        ),
    ]
